spring.application.name=emp_sp_camel
camel.springboot.name=EmployeeCamelApp
camel.springboot.main-run-controller=true

# Oracle DB
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=empuser
spring.datasource.password=empuser123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

